In [1]:
import pandas as pd
google = pd.read_csv("google-play-store.csv")

In [2]:
google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62694 entries, 0 to 62693
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   app_id             62694 non-null  object
 1   title              62694 non-null  object
 2   reviews            62683 non-null  float64
 3   ratings            62683 non-null  float64
 4   min_installs       62694 non-null  int64
 5   score              62683 non-null  float64
 6   offers_iap         62694 non-null  bool
 7   ad_supported       62694 non-null  bool
 8   released           61848 non-null  object
 9   ratings_per_day    62694 non-null  int64
 10  genre              62693 non-null  object
 11  genre_id           62693 non-null  object
 12  price              62694 non-null  float64
 13  rating_one_star    62694 non-null  int64
 14  rating_two_star    62694 non-null  int64
 15  rating_three_star  62694 non-null  int64
 16  rating_four_star   62694 non-null  int64
 17  rating_five_star   62694 non-null  int64
dtypes: bool(2), float64(4), int64(7), object(5)
memory usage: 7.8+ MB

In [3]:
#كولوم ريليسد دا الداتا فية ديت تايم لكن التايب بتاعه ستير فلازم يتحول لديت تايم
google["released"] = pd.to_datetime(google["released"])

In [4]:
#عايزة اشوف شكل الداتا فريم علشان افهم كل كولم اى بالظبط نوع الداتا اللى فية 
google.head()

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
0,com.prettyteengames.royal.princess.wedding.mak...,Royal Princess Wedding Makeover and Dress Up,375.0,1023.0,100000,4.179863,True,True,2017-12-20,3,Casual,GAME_CASUAL,0.0,115,31,98,90,689
1,com.MayGreenStudio.dressup,Momo's Dressup,13492.0,25974.0,1000000,4.711096,False,True,2017-03-07,42,Casual,GAME_CASUAL,0.0,673,213,806,2561,21721
2,air.theflash.f2game.PrettyGirl23,Princess Pretty Girl,1974.0,4610.0,500000,4.295445,False,True,2015-01-18,3,Casual,GAME_CASUAL,0.0,382,206,287,528,3207
3,air.com.dressupone.animeschooluniforms,Anime School Uniforms,2586.0,6081.0,500000,4.209505,False,True,2013-08-20,3,Casual,GAME_CASUAL,0.0,628,193,524,668,4068
4,air.theflash.f2game.PrettyGirl7,Wedding Pretty girl,1409.0,3728.0,500000,4.195011,False,True,2014-09-01,2,Casual,GAME_CASUAL,0.0,358,185,300,414,2471

In [5]:
#هجممع عدد كل الميسينج فاليوز علشان اهندلها
google.isnull().sum()

app_id                 0
title                  0
reviews               11
ratings               11
min_installs           0
score                 11
offers_iap             0
ad_supported           0
released             846
ratings_per_day        0
genre                  1
genre_id               1
price                  0
rating_one_star        0
rating_two_star        0
rating_three_star      0
rating_four_star       0
rating_five_star       0
dtype: int64

In [6]:
#همسك كولوم كولم اعمل فيل نا بالميدن لانة هو اللى مش هيتأثر بالاوت لاير زى المين و هيخلى الداتا قريبة للصح 
#عملت جروب باى جينرى للرفيورز و حسبت الميدين ليها و هعمل بقيمة الميدن فيل للنل فاليوز و هكذا فى كل كولم
#استخدمنا فنكشن تراتنسفورم علشان نحافظ على الداتا لكل رو زى فكرة الويندو فنكشن هتعمل عملية على جروب كبير لكن هتحافظ على ديتيلز لكل رو 
google['reviews'] = google['reviews'].fillna(
    google.groupby('genre')['reviews'].transform('median')
)
google['ratings'] = google['ratings'].fillna(
    google.groupby('genre')['ratings'].transform('median')
)
google['score'] = google['score'].fillna(
    google.groupby('genre')['score'].transform('median')
)

In [7]:
#حسبت المدين للكولوم ريليس و هعمل فيل للميسينج فاليو بيه و جايبة الميدين لكل جينيرى 
google['released'] = google['released'].fillna(
    google.groupby('genre')['released'].transform('median')
)

In [9]:
google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62694 entries, 0 to 62693
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   app_id             62694 non-null  object
 1   title              62694 non-null  object
 2   reviews            62694 non-null  float64
 3   ratings            62694 non-null  float64
 4   min_installs       62694 non-null  int64
 5   score              62694 non-null  float64
 6   offers_iap         62694 non-null  bool
 7   ad_supported       62694 non-null  bool
 8   released           62694 non-null  datetime64[ns]
 9   ratings_per_day    62694 non-null  int64
 10  genre              62693 non-null  object
 11  genre_id           62693 non-null  object
 12  price              62694 non-null  float64
 13  rating_one_star    62694 non-null  int64
 14  rating_two_star    62694 non-null  int64
 15  rating_three_star  62694 non-null  int64
 16  rating_four_star   62694 non-null  int64
 17  rating_five_star   62694 non-null  int64
dtypes: bool(2), datetime64[ns](1), float64(4), int64(7), object(4)
memory usage: 7.8+ MB

In [10]:
#اشوف الرو الفاضى و اعرف هل فيه داتا ولا لاء
google[google['genre'].isnull()]

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
2261,com.singlebyte.devshortcut,Developer Options,280.0,1362.0,100000,4.300294,False,False,2013-02-04,0,NaN,NaN,0.0,114,59,91,138,960

In [11]:
#مليت الفليو الميسنج بان نون لان اسم الاب موجود و ممكن احتاجها فى التحليل لو هصنف اسم الاب فيما بعد
google['genre'] = google['genre'].fillna('Unknown')
google['genre_id'] = google['genre_id'].fillna(-1)

In [12]:
#غيرت اسم الداتا فريم 
apps_df = google

In [13]:
#عملت جروب باى جينرى بالكولوم ريت بير ديت و حسبت المين و رتبت الفليوز ديسيندنج
apps_df.groupby('genre')['ratings_per_day'].mean().sort_values(ascending=False)

genre
Strategy                   258.185996
Action                     247.476386
Racing                     188.293900
Arcade                     158.313333
Social                     143.052632
Casual                     138.944697
Word                       136.277778
Role Playing               127.422414
Communication              120.518760
Adventure                  102.709552
Video Players & Editors     83.897849
Sports                      79.962211
Puzzle                      72.210134
Trivia                      64.151111
Simulation                  63.355017
Photography                 55.830139
Casino                      49.992718
Weather                     48.910569
Music                       46.621005
Board                       39.562914
Tools                       34.911176
Shopping                    30.974800
Card                        30.123267
Personalization             23.774475
Entertainment               21.762887
Dating                      21.285714
Music & Audio               21.066721
Productivity                20.542247
Comics                      18.583815
Libraries & Demo            16.910256
Maps & Navigation           11.621501
Travel & Local              11.089233
Art & Design                10.880383
News & Magazines            10.426343
Educational                 10.106838
Health & Fitness             9.447615
Finance                      8.448537
Lifestyle                    7.244548
House & Home                 5.379167
Beauty                       5.365854
Parenting                    4.704225
Auto & Vehicles              4.594077
Books & Reference            4.476737
Food & Drink                 3.903188
Education                    3.749588
Business                     3.458962
Medical                      1.168548
Events                       1.152941
Unknown                      0.000000
Name: ratings_per_day, dtype: float64

In [14]:
#عملت جروب باى جينرى بالكولوم ريت بير ديت و حسبت المين و رتبت الفاليوز من الصغير للكبير
apps_df.groupby('genre')['ratings_per_day'].mean().sort_values()

genre
Unknown                      0.000000
Events                       1.152941
Medical                      1.168548
Business                     3.458962
Education                    3.749588
Food & Drink                 3.903188
Books & Reference            4.476737
Auto & Vehicles              4.594077
Parenting                    4.704225
Beauty                       5.365854
House & Home                 5.379167
Lifestyle                    7.244548
Finance                      8.448537
Health & Fitness             9.447615
Educational                 10.106838
News & Magazines            10.426343
Art & Design                10.880383
Travel & Local              11.089233
Maps & Navigation           11.621501
Libraries & Demo            16.910256
Comics                      18.583815
Productivity                20.542247
Music & Audio               21.066721
Dating                      21.285714
Entertainment               21.762887
Personalization             23.774475
Card                        30.123267
Shopping                    30.974800
Tools                       34.911176
Board                       39.562914
Music                       46.621005
Weather                     48.910569
Casino                      49.992718
Photography                 55.830139
Simulation                  63.355017
Trivia                      64.151111
Puzzle                      72.210134
Sports                      79.962211
Video Players & Editors     83.897849
Adventure                  102.709552
Communication              120.518760
Role Playing               127.422414
Word                       136.277778
Casual                     138.944697
Social                     143.052632
Arcade                     158.313333
Racing                     188.293900
Action                     247.476386
Strategy                   258.185996
Name: ratings_per_day, dtype: float64

In [15]:
#عملت جروب باى للجينرى بالكولوم ريت بير ديت و هاخد اعلى اندكس رقم الصف اما الفنكشن لوك رجعتلى بياتات الرو كاملة 
apps_df.loc[apps_df.groupby('genre')['ratings_per_day'].idxmax()]

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
52236,com.dts.freefireth,Garena Free Fire,5295447.0,10525586.0,100000000,4.541122,True,False,2017-12-07,30957,Action,GAME_ACTION,0.0,612184,152257,470918,982612,8307615
15947,com.nianticlabs.pokemongo,Pokémon GO,4302227.0,10899120.0,100000000,4.098553,True,False,2016-07-06,12807,Adventure,GAME_ADVENTURE,0.0,1444499,389747,789992,1297760,6977122
12091,com.kiloo.subwaysurf,Subway Surfers,8939651.0,28564566.0,1000000000,4.494330,True,True,2012-09-20,12774,Arcade,GAME_ARCADE,0.0,1439764,676712,1572821,3509425,21365844
5182,com.canva.editor,"Canva: Graphic design & poster, invitation maker",147147.0,338367.0,10000000,4.731097,True,False,2017-11-27,989,Art & Design,ART_AND_DESIGN,0.0,4450,1912,10069,47314,274622
26482,com.google.android.projection.gearhead,"Android Auto - Google Maps, Media & Messaging",160302.0,350891.0,10000000,4.220020,False,False,2015-03-19,264,Auto & Vehicles,AUTO_AND_VEHICLES,0.0,16934,9398,31928,113902,178729
30629,com.infokombinat.hairstyle2,Best Hairstyles step by step,26669.0,56059.0,5000000,4.444906,True,True,2017-05-15,103,Beauty,BEAUTY,0.0,3272,928,3882,7482,40495
17229,com.ludo.king,Ludo King™,696620.0,2110430.0,100000000,4.439999,True,True,2016-12-17,3071,Board,GAME_BOARD,0.0,121407,34460,140556,311723,1502284
24103,com.google.android.apps.books,Google Play Books,264582.0,1458856.0,1000000000,3.920621,False,False,2010-12-06,504,Books & Reference,BOOKS_AND_REFERENCE,0.0,207659,70881,149652,232075,798589
27690,com.ubercab.driver,Uber Driver,357338.0,1387151.0,10000000,4.330991,False,False,2014-11-14,955,Business,BUSINESS,0.0,131646,39295,78206,127136,1010868
35814,jp.konami.duellinks,Yu-Gi-Oh! Duel Links,599370.0,1547989.0,10000000,4.647471,True,True,2017-01-10,2327,Card,GAME_CARD,0.0,64180,19116,48632,134379,1281682
27259,com.zynga.livepoker,Zynga Poker – Texas Holdem,545131.0,2066958.0,50000000,4.448444,True,True,2010-12-21,718,Casino,GAME_CASINO,0.0,120659,39487,111673,315599,1479540
24638,com.king.candycrush4,Candy Crush Friends Saga,125018.0,464798.0,10000000,4.655672,True,False,2018-10-10,17876,Casual,GAME_CASUAL,0.0,4960,3263,23466,83482,349627
29947,com.naver.linewebtoon,LINE WEBTOON - Free Comics,371201.0,1069812.0,10000000,4.522142,False,True,2014-07-01,674,Comics,COMICS,0.0,34760,21241,77961,152533,783317
5293,com.facebook.orca,Messenger – Text and Video Chat for Free,15404150.0,59965894.0,1000000000,4.059807,True,False,2014-01-30,34482,Communication,COMMUNICATION,0.0,7366642,2357735,5586528,8666649,35988340
25077,com.jaumo.prime,Find Real Love — YouLove Premium Dating,85814.0,243593.0,10000000,4.541715,True,True,2016-12-13,352,Dating,DATING,0.0,11523,3296,11594,32467,184713
6333,com.duolingo,Duolingo: Learn Languages Free,2522372.0,6672540.0,100000000,4.718288,True,True,2013-05-29,3361,Education,EDUCATION,0.0,78222,45682,166856,1096090,5285690
19299,com.tocaboca.tocakitchen2,Toca Kitchen 2,452451.0,1063463.0,50000000,4.487507,False,False,2015-05-25,844,Educational,GAME_EDUCATIONAL,0.0,64119,22204,57034,107861,812245
8468,com.google.android.play.games,Google Play Games,1818985.0,7967973.0,1000000000,4.286302,False,False,2013-07-24,4130,Entertainment,ENTERTAINMENT,0.0,760102,215180,553110,894559,5545022
30639,com.janasena.events,JanaSena News & Events,1940.0,4375.0,50000,4.963429,False,False,2018-04-11,21,Events,EVENTS,0.0,25,3,9,33,4305
10842,com.phonepe.app,"PhonePe – UPI Payments, Recharges & Money Tran...",591511.0,1553830.0,50000000,4.489330,False,False,2016-10-14,2069,Finance,FINANCE,0.0,78973,20172,70316,276455,1107914
26560,com.ubercab.eats,Uber Eats: Local Food Delivery,195185.0,558733.0,10000000,4.187075,False,False,2016-02-29,570,Food & Drink,FOOD_AND_DRINK,0.0,79932,11504,19771,60426,387100
5996,com.popularapp.periodcalendar,Period Tracker - Period Calendar Ovulation Tra...,1110581.0,4662795.0,100000000,4.778903,False,True,2012-03-16,1923,Health & Fitness,HEALTH_AND_FITNESS,0.0,43616,30225,109933,545925,3933096
9772,tv.peel.app,Peel Universal Smart TV Remote Control,259013.0,665813.0,100000000,3.950983,True,True,2012-05-11,281,House & Home,HOUSE_AND_HOME,0.0,118669,17527,36122,98948,394547
15649,com.equalizer.volume.music.bass.booster.tool,Equalizer Pro - Volume Booster & Bass Booster,2700.0,7971.0,100000,4.615230,False,True,2018-09-18,169,Libraries & Demo,LIBRARIES_AND_DEMO,0.0,306,53,281,1122,6209
25060,com.tinder,Tinder®,745599.0,2991518.0,100000000,3.980804,True,True,2013-07-15,1542,Lifestyle,LIFESTYLE,0.0,354951,114785,303179,678427,1540176
21333,com.ubercab,Uber,1626913.0,5394222.0,100000000,4.186175,False,False,2010-10-28,1841,Maps & Navigation,MAPS_AND_NAVIGATION,0.0,630618,158215,337818,717201,3550370
6077,com.lbrc.PeriodCalendar,My Calendar - Period Tracker,46241.0,169781.0,5000000,4.667772,True,True,2015-08-16,144,Medical,MEDICAL,0.0,1409,1031,7522,32633,127186
28158,com.youmusic.magictiles,Magic Tiles 3,293749.0,715197.0,100000000,4.485986,True,True,2017-02-24,1157,Music,GAME_MUSIC,0.0,44036,10280,41811,77015,542055
7084,com.spotify.music,Spotify Music,3833382.0,12875935.0,100000000,4.556335,False,True,2014-05-27,7938,Music & Audio,MUSIC_AND_AUDIO,0.0,535469,217387,551983,1814605,9756491
5923,com.twitter.android,Twitter,2990720.0,12126436.0,500000000,4.294944,False,True,2010-04-30,3899,News & Magazines,NEWS_AND_MAGAZINES,0.0,880733,371642,877095,2157768,7839198
6093,com.babycenter.pregnancytracker,Pregnancy Tracker & Countdown to Baby Due Date,237196.0,709601.0,10000000,4.697687,False,True,2011-03-11,253,Parenting,PARENTING,0.0,8966,5750,18765,123878,552242
12623,com.ksmobile.launcher,"CM Launcher 3D - Themes, Wallpapers",2140426.0,7200749.0,100000000,4.547349,False,True,2014-12-05,5035,Personalization,PERSONALIZATION,0.0,274943,109430,427023,977321,5412032
53181,com.google.android.apps.photos,Google Photos,3205918.0,12507540.0,1000000000,4.529529,False,False,2015-05-28,9958,Photography,PHOTOGRAPHY,0.0,434524,212933,701005,2105525,9053553
4881,com.surpax.ledflashlight.panel,Super-Bright LED Flashlight,2112580.0,8966715.0,500000000,4.594786,False,True,2012-08-22,3958,Productivity,PRODUCTIVITY,0.0,317637,169092,396058,1063502,7020426
16572,com.game5mobile.lineandwater,Happy Glass,94886.0,273906.0,10000000,4.313429,True,True,2018-08-28,4028,Puzzle,GAME_PUZZLE,0.0,21161,5827,21410,43111,182397
26697,com.skgames.trafficrider,Traffic Rider,2114891.0,6399198.0,100000000,4.679771,True,True,2016-01-11,6224,Racing,GAME_RACING,0.0,148580,60109,239467,795626,5155416
16920,com.nekki.shadowfight3,Shadow Fight 3,789649.0,1741570.0,10000000,4.435276,True,True,2017-11-16,4933,Role Playing,GAME_ROLE_PLAYING,0.0,139055,36647,76031,165283,1324554
16620,com.contextlogic.wish,Wish - Shopping Made Fun,2501338.0,6876996.0,100000000,4.466313,False,False,2012-07-26,3000,Shopping,SHOPPING,0.0,309821,105176,400806,1313739,4747454
13582,com.brokenreality.planemerger.android,Merge Plane - Click & Idle Tycoon,319636.0,998167.0,10000000,4.729398,True,True,2018-03-25,4456,Simulation,GAME_SIMULATION,0.0,24401,6707,38194,75993,852872
6796,com.facebook.lite,Facebook Lite,2673427.0,9483266.0,500000000,4.288608,False,True,2018-03-15,40526,Social,SOCIAL,0.0,671534,323937,860488,1367394,6259913
15963,com.firsttouchgames.dls3,Dream League Soccer 2018,4722102.0,10421561.0,100000000,4.596034,True,True,2016-04-07,11074,Sports,GAME_SPORTS,0.0,377022,136033,492509,1308759,8107238
12054,com.supercell.clashofclans,Clash of Clans,17895834.0,46411254.0,100000000,4.603980,True,False,2013-09-30,24938,Strategy,GAME_STRATEGY,0.0,1990796,714343,1791778,4690030,37224307
4484,com.cleanmaster.mguard,Clean Master- Space Cleaner & Antivirus,11064681.0,43494715.0,500000000,4.657593,True,True,2012-09-07,19339,Tools,TOOLS,0.0,954777,511095,1709871,6120765,34198207
28056,com.gojek.app,"GO-JEK - Ojek Taxi Booking, Delivery and Payment",546781.0,1721626.0,10000000,4.406891,False,False,2015-02-02,1253,Travel & Local,TRAVEL_AND_LOCAL,0.0,90155,44668,129543,267402,1189858
15216,com.etermax.preguntados.lite,Trivia Crack,1646244.0,6546008.0,100000000,4.465654,True,True,2013-10-24,3563,Trivia,GAME_TRIVIA,0.0,225217,113647,407359,1441304,4358481
2261,com.singlebyte.devshortcut,Developer Options,280.0,1362.0,100000,4.300294,False,False,2013-02-04,0,Unknown,-1,0.0,114,59,91,138,960
4967,com.google.android.youtube,YouTube,9135212.0,30385156.0,1000000000,4.318781,False,True,2010-10-20,10345,Video Players & Editors,VIDEO_PLAYERS,0.0,2559874,860074,1958187,3962843,21044178
8564,com.chanel.weather.forecast.accu,Weather forecast,93049.0,352522.0,5000000,4.763297,False,True,2018-03-20,1539,Weather,WEATHER,0.0,2709,1458,7889,52455,288011
9644,com.bitmango.go.wordcookies,Word Cookies™,782753.0,2132936.0,10000000,4.627806,True,True,2016-12-08,3064,Word,GAME_WORD,0.0,17022,10694,116733,460230,1528257

In [ ]:
#عملت جروب باى جينرى  على  عمود ريتنج بيرداى و حسبت المتوسط علشان ميتاثرش بالاوت لاير و عملت سورت فاليو من الكبير للصغير علشان اعرف مين اكترالتطبيقات اعلى متوسط  تقيمات يومية
apps_df.groupby('genre')['ratings_per_day'].median().sort_values(ascending=False)

genre
Word                       23.5
Racing                     22.0
Strategy                   20.0
Action                     20.0
Role Playing               17.0
Casino                     14.0
Arcade                     13.0
Casual                     12.0
Adventure                  12.0
Simulation                  9.0
Puzzle                      7.5
Music                       6.0
Dating                      5.0
Trivia                      4.0
Card                        4.0
Board                       4.0
Video Players & Editors     4.0
Weather                     3.0
Photography                 3.0
Social                      2.0
Art & Design                1.0
Tools                       1.0
Sports                      1.0
Educational                 1.0
Comics                      1.0
Entertainment               1.0
Personalization             1.0
Libraries & Demo            0.5
Communication               0.0
Auto & Vehicles             0.0
Beauty                      0.0
Books & Reference           0.0
Business                    0.0
Education                   0.0
News & Magazines            0.0
Medical                     0.0
Parenting                   0.0
Maps & Navigation           0.0
Health & Fitness            0.0
House & Home                0.0
Lifestyle                   0.0
Events                      0.0
Finance                     0.0
Food & Drink                0.0
Music & Audio               0.0
Shopping                    0.0
Productivity                0.0
Travel & Local              0.0
Unknown                     0.0
Name: ratings_per_day, dtype: float64

In [ ]:
#عايزة اعرف مين التطبيقات اللى فيها خاصية الدفع من التطبيق اول حاجه فلترة بكولوم الابرايس من الداتا فريم لو البرايس اكبر من 0 و خزنتها في الداتا فريم بدل م ترجع بولين فاليبو 
#بعد كدا عملت جروب باى جينرى بالكولوم ريتنج بير داى و حسبت الميدين و رتبت الفليوز من الكبير للصغير علشان اعرف كل جينرى بيحقق اعلى معدل تقييمات يومية
paid_apps = apps_df[apps_df['price'] > 0]
paid_apps.groupby('genre')['ratings_per_day'].median().sort_values(ascending=False)

genre
Word                       18.5
Adventure                   6.5
Simulation                  4.5
Role Playing                1.0
Racing                      0.5
Action                      0.0
Arcade                      0.0
Art & Design                0.0
Business                    0.0
Card                        0.0
Casino                      0.0
Casual                      0.0
Auto & Vehicles             0.0
Beauty                      0.0
Board                       0.0
Books & Reference           0.0
Education                   0.0
Dating                      0.0
Communication               0.0
Comics                      0.0
Educational                 0.0
Entertainment               0.0
Events                      0.0
Finance                     0.0
Lifestyle                   0.0
Maps & Navigation           0.0
Medical                     0.0
Music                       0.0
Food & Drink                0.0
Health & Fitness            0.0
House & Home                0.0
Libraries & Demo            0.0
Personalization             0.0
Parenting                   0.0
News & Magazines            0.0
Music & Audio               0.0
Puzzle                      0.0
Productivity                0.0
Shopping                    0.0
Photography                 0.0
Social                      0.0
Sports                      0.0
Tools                       0.0
Strategy                    0.0
Travel & Local              0.0
Trivia                      0.0
Video Players & Editors     0.0
Weather                     0.0
Name: ratings_per_day, dtype: float64

In [ ]:
# حسبنا متوسط التقييمات لكل جنرى و سورت للفلاليو من الكبير للصغير علشان اعرف انهى تطبيقات بتاخد اعلى معدل تقييمات 
apps_df.groupby('genre')['ratings'].mean().sort_values(ascending= False)

genre
Strategy                   304020.808534
Social                     292554.897129
Communication              254248.665579
Racing                     224220.573013
Action                     196421.164271
Arcade                     167421.695556
Casual                     154663.606818
Video Players & Editors    120541.865591
Word                        98660.813131
Role Playing                89314.362069
Weather                     84435.451220
Adventure                   82928.460039
Photography                 79647.282882
Sports                      79194.342897
Trivia                      70954.644444
Casino                      67599.412621
Puzzle                      60268.260060
Shopping                    58371.854525
Tools                       54301.576066
Simulation                  53439.590959
Music                       44470.127854
Board                       40307.981788
Card                        39052.077042
Productivity                38475.704268
Music & Audio               33368.813344
Maps & Navigation           31003.279955
Personalization             30148.246928
Travel & Local              28322.542773
Dating                      27304.040816
Entertainment               24828.777909
News & Magazines            22900.637782
Libraries & Demo            21051.705128
Comics                      18852.913295
Health & Fitness            12486.677482
House & Home                11572.583333
Finance                     11518.936932
Books & Reference            9960.886959
Educational                  9691.621795
Lifestyle                    9113.578477
Parenting                    8658.638498
Food & Drink                 7182.864227
Art & Design                 5965.229665
Business                     5816.281929
Education                    4577.406114
Auto & Vehicles              3441.716028
Beauty                       3303.308943
Medical                      1768.773514
Unknown                      1362.000000
Events                        897.717647
Name: ratings, dtype: float64

In [ ]:
# رتبنا الريفيوز من الكبير للصغير و جبنا اكبر 5 تقييمات 
apps_df.sort_values('reviews', ascending=False).head(5)

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
5298,com.facebook.katana,Facebook,22053770.0,81284862.0,1000000000,4.073720,True,True,2017-02-16,0,Social,SOCIAL,0.0,9658715,3368101,7164984,12223419,48869643
7119,com.instagram.android,Instagram,21702496.0,71203510.0,1000000000,4.516777,False,True,2012-04-03,29594,Social,SOCIAL,0.0,2843778,1306353,3872506,11368004,51812869
5058,com.whatsapp,WhatsApp Messenger,19031005.0,75031471.0,1000000000,4.408304,False,False,2010-10-18,25529,Communication,COMMUNICATION,0.0,4603522,1875312,4755810,10844172,52952655
12054,com.supercell.clashofclans,Clash of Clans,17895834.0,46411254.0,100000000,4.603980,True,False,2013-09-30,24938,Strategy,GAME_STRATEGY,0.0,1990796,714343,1791778,4690030,37224307
5293,com.facebook.orca,Messenger – Text and Video Chat for Free,15404150.0,59965894.0,1000000000,4.059807,True,False,2014-01-30,34482,Communication,COMMUNICATION,0.0,7366642,2357735,5586528,8666649,35988340

In [ ]:
# بتحسب كام مرة القيمة فى عمود offers_iapو كل مرة ترو بيقى التطبيق بيدعم و الفولس لا يدعم الدفع
apps_df['offers_iap'].value_counts()

offers_iap
False    49091
True     13603
Name: count, dtype: int64

In [ ]:
# جمعنا عدد مرات التحميل لكل جنرى 
apps_df.groupby('genre')['min_installs'].sum()

genre
Action                      5159334100
Adventure                    971827210
Arcade                      5563164090
Art & Design                 281826260
Auto & Vehicles              119088810
Beauty                        33961170
Board                        930719100
Books & Reference           2308208930
Business                    1074434380
Card                         757560950
Casino                       577525500
Casual                      6337830360
Comics                        91482060
Communication              12171306200
Dating                       168867510
Education                   1155849465
Educational                  989422731
Entertainment               4772695821
Events                         4590470
Finance                      940519160
Food & Drink                 218922691
Health & Fitness            1672767920
House & Home                 257685770
Libraries & Demo              61944950
Lifestyle                   1237697540
Maps & Navigation            907767740
Medical                      102845571
Music                        555093955
Music & Audio               4132745460
News & Magazines            2719045176
Parenting                     54958200
Personalization             2838407325
Photography                 5939279081
Productivity               10529523940
Puzzle                      3420318450
Racing                      4191202110
Role Playing                 815685525
Shopping                    1758130980
Simulation                  3214610210
Social                      5305541910
Sports                      2688151830
Strategy                    1437786500
Tools                      19324157224
Travel & Local              3420082880
Trivia                       380916650
Unknown                         100000
Video Players & Editors     4797577910
Weather                      672528500
Word                         558185000
Name: min_installs, dtype: int64

In [ ]:
# عايزة اعرف اقدم واحدث تاريخ
apps_df['released'].agg(['min', 'max'])

min   2010-01-28
max   2018-11-12
Name: released, dtype: datetime64[us]

In [ ]:
#بنفلتر الريفيوز الاكبر من 10000 للعمود ريتنج بير داى و فى الاخر حبنا المتوسط علشان اعرف متوسط التقيمات اليومية للتطبيقات اللى عندها مراجعات كبيرة
apps_df[apps_df['reviews'] > 10000]['ratings_per_day'].mean()

np.float64(328.08230958230956)

In [ ]:
# جروب باى على عمود ريتنج و حسبنا المتوسط و رتبنا النتائج من الكبير للصغير علشان اخد اكبر 3 تطبيقات ليها ريتنج عالى
apps_df.groupby('genre')['ratings'].mean().sort_values(ascending=False).head(3)

genre
Strategy         304020.808534
Social           292554.897129
Communication    254248.665579
Name: ratings, dtype: float64

In [ ]:
#شرطين لازم يتحققوا سوا الاول التطبيقات اللى بتدعم الاعلانات و التانى التطبيقات اللى بتدعم الدفع من التطبيق 
# و حسبنا متوسط التطبيقات اللى بتعدم الرشطين ثم حولناها المتوسط لنسبة مئوية
((apps_df['ad_supported'] == True) & 
 (apps_df['offers_iap'] == True)).mean() * 100

np.float64(16.963345774715282)

In [ ]:
#عايزن نحسب اكتر سنه اتحقق فيها تحميلات للتطبيقات
apps_df['released'].dt.year.value_counts().idxmax()

np.int32(2018)

In [ ]:
# معامل الارتباط بين الرفيوز و الريتنج و عملنا الارتباط دا بعد جروبي باى جنرى 
#   لوك فانكشن علشان ترجع بيانات الرو اللى اتحقق فيه معامل الارتباط لكل جنرى بين ريفيوز و الريتنجس  
correlation_by_genre = apps_df.groupby('genre')[['reviews', 'ratings']].corr()

correlation_by_genre.loc[ : , ('reviews', 'ratings')]

                                  reviews   ratings
genre
Action                  reviews  1.000000  0.976527
                        ratings  0.976527  1.000000
Adventure               reviews  1.000000  0.985165
                        ratings  0.985165  1.000000
Arcade                  reviews  1.000000  0.992306
...                                   ...       ...
Video Players & Editors ratings  0.993777  1.000000
Weather                 reviews  1.000000  0.994636
                        ratings  0.994636  1.000000
Word                    reviews  1.000000  0.992710
                        ratings  0.992710  1.000000

[98 rows x 2 columns]

In [ ]:
# جربنا الريتنج فى الريفيو لكل نوع جنرى و جمعنا النتيجة و قسمناها على الرفيوز لكل جنرى و مع تجميع النتيجة علشان نعرف متوسط الويت 
weighted_avg = (
    (apps_df['ratings'] * apps_df['reviews'])
    .groupby(apps_df['genre'])
    .sum()
    /
    apps_df['reviews'].groupby(apps_df['genre']).sum()
)

weighted_avg

genre
Action                     3.881101e+06
Adventure                  4.107444e+06
Arcade                     7.456326e+06
Art & Design               1.557658e+05
Auto & Vehicles            1.254883e+05
Beauty                     3.435117e+04
Board                      7.701927e+05
Books & Reference          7.915964e+05
Business                   4.576586e+05
Card                       6.914190e+05
Casino                     6.315197e+05
Casual                     6.926374e+06
Comics                     4.779676e+05
Communication              3.257192e+07
Dating                     1.856416e+05
Education                  1.742543e+06
Educational                2.735333e+05
Entertainment              2.189184e+06
Events                     5.594167e+03
Finance                    4.322802e+05
Food & Drink               3.192776e+05
Health & Fitness           8.667980e+05
House & Home               2.874406e+05
Libraries & Demo           2.510926e+05
Lifestyle                  5.816921e+05
Maps & Navigation          3.440279e+06
Medical                    5.566114e+04
Music                      4.405135e+05
Music & Audio              3.036249e+06
News & Magazines           5.544394e+06
Parenting                  3.151269e+05
Personalization            3.149557e+06
Photography                3.679161e+06
Productivity               2.188371e+06
Puzzle                     6.773866e+05
Racing                     3.180149e+06
Role Playing               8.073075e+05
Shopping                   3.484894e+06
Simulation                 1.590139e+06
Social                     4.885605e+07
Sports                     4.273725e+06
Strategy                   2.204244e+07
Tools                      1.025833e+07
Travel & Local             2.787447e+06
Trivia                     2.994270e+06
Unknown                    1.362000e+03
Video Players & Editors    1.152439e+07
Weather                    1.045613e+06
Word                       8.127713e+05
dtype: float64

In [ ]:
# فلترنا الداتا علش\ان استبعد اللى بتساوى صفر 
# نحسب النسبة
# نجيب اعلى التطبيقات لوك ترجعلنا بيانات الرو اللى معملو فية جروب باى جنرى مع الكولوم ريشسيو و اخدنا اعلى اندكس 
#اخر حاجه عرضت التوم اب بالكوم  تايتل و نوع و الريشيو يعنى جدول مختصر 
apps_df = apps_df[apps_df['ratings'] > 0]
apps_df['ratio'] = apps_df['score'] / apps_df['ratings']
top_apps = apps_df.loc[apps_df.groupby('genre')['ratio'].idxmax()]
top_apps[['title', 'genre', 'ratio']]

,title,genre,ratio
19046,Star Combat Online,Action,5.000000
53005,Astronaut VR,Adventure,1.555555
47995,Retro GEN Pro - MD Emulator,Arcade,5.000000
30627,Graffiti Alphabet Letters Drawing Ideas,Art & Design,5.000000
15812,Smobile,Auto & Vehicles,5.000000
25166,Makeup ideas step by step,Beauty,5.000000
58987,55 Shogi,Board,2.250000
348,Man O Salwa Novel,Books & Reference,5.000000
99,Purposeful Project Management,Business,5.000000
43738,Solitaire Pets Adventure - Classic Card Game,Card,5.000000
45605,Mississippi Stud Poker,Casino,0.937500
39790,Pups Patrol - Pixie Painting Book,Casual,5.000000
54428,Grand Rapids Comic Convention,Comics,1.500000
1702,SIXTYconnect,Communication,5.000000
5276,Chpoking - Знакомства для взрослых,Dating,5.000000
68,Medical Terminology,Education,5.000000
31370,Sound Brain Training,Educational,5.000000
416,Together is more,Entertainment,5.000000
39337,Buruuj Task Manager,Events,2.500000
1076,LIGHT FX,Finance,5.000000
10084,Jom Masak,Food & Drink,5.000000
7366,my mhealth,Health & Fitness,5.000000
26829,Lamptitude BLE,House & Home,5.000000
6089,Ionic 3 UI/UX Components & Multipurpose Template,Libraries & Demo,5.000000
946,CHERISH AI,Lifestyle,5.000000
747,Team Meetup,Maps & Navigation,5.000000
157,Winnie Vet Clinic,Medical,5.000000
28715,8 Bit Conservatory - A Music Learning Game,Music,5.000000
26612,Mozart Sleep Music,Music & Audio,5.000000
239,Stuff Radio : Stuff You Should Know,News & Magazines,5.000000
60458,LullabyGarden Offline High Quality Lullabies,Parenting,5.000000
551,Detroit Red Wings Wallpaper,Personalization,5.000000
17163,SI Smartphone Printer,Photography,5.000000
2766,Mercer Events,Productivity,5.000000
1216,2048 Fever,Puzzle,5.000000
52496,Swish,Racing,0.484375
13474,Rogue Grinders: Dungeon Crawler Roguelike RPG,Role Playing,5.000000
21404,Zellr,Shopping,5.000000
51761,悪役令嬢、旅に出る ～そして彼女は、伝説となる～＊恋愛・乙女ゲーム,Simulation,5.000000
8454,Kirtan Sohila,Social,5.000000
3553,3D Pool Game Learning,Sports,5.000000
2072,Knights and Glory - Tactical Battle Simulator,Strategy,5.000000
976,AlsoEnergy,Tools,5.000000
22149,Meritus Hospitality,Travel & Local,5.000000
3410,Quiz Racing,Trivia,5.000000
2261,Developer Options,Unknown,0.003157
23973,Media Player for JW Broadcasting (Unofficial),Video Players & Editors,2.500000
55310,NOAA Aviation PRO Live Weather,Weather,5.000000
43202,Bible Word Search,Word,0.212810